# Generated by Django 2.2 on 2019-04-23 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trivia', '0003_auto_20190417_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
                ('p1life', models.IntegerField(default=1)),
                ('p2life', models.IntegerField(default=1)),
                ('question', models.TextField()),
                ('answers', models.TextField()),
                ('correctAnswer', models.IntegerField(default=0)),
                ('timeUpdated', models.TimeField()),
                ('p1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to=settings.AUTH_USER_MODEL)),
                ('p2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
