# Generated by Django 2.2 on 2019-04-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0004_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='timeUpdated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
