# Generated by Django 2.2 on 2019-04-23 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0005_auto_20190423_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='p2',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='p2', to=settings.AUTH_USER_MODEL),
        ),
    ]
