# Generated by Django 2.2 on 2019-04-23 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0007_auto_20190423_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('choice1', models.TextField()),
                ('choice2', models.TextField()),
                ('choice3', models.TextField()),
                ('choice4', models.TextField()),
                ('correctChoice', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='game',
            name='correctAnswer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='p1life',
        ),
        migrations.RemoveField(
            model_name='game',
            name='p2life',
        ),
        migrations.AddField(
            model_name='game',
            name='p1lives',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='game',
            name='p2lives',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triviaQuestion', to='trivia.TriviaQuestion'),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
