# Generated by Django 2.2 on 2019-04-23 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0008_auto_20190423_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triviaQuestion', to='trivia.TriviaQuestion'),
        ),
    ]
