# Generated by Django 2.2 on 2019-04-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0010_triviaquestion_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='p1choice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='p2choice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='questionNum',
            field=models.IntegerField(default=0),
        ),
    ]
