# Generated by Django 2.2 on 2019-04-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0011_auto_20190423_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.IntegerField(default=0),
        ),
    ]
