# Generated by Django 2.2 on 2019-04-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0012_game_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='timeUpdated',
        ),
        migrations.AddField(
            model_name='game',
            name='questionTime',
            field=models.IntegerField(default=0),
        ),
    ]
