# Generated by Django 2.2 on 2019-04-24 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trivia', '0013_auto_20190424_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('choice', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='p1choice',
        ),
        migrations.RemoveField(
            model_name='game',
            name='p1lives',
        ),
        migrations.RemoveField(
            model_name='game',
            name='p2choice',
        ),
        migrations.RemoveField(
            model_name='game',
            name='p2lives',
        ),
        migrations.AlterField(
            model_name='game',
            name='p1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='trivia.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='p2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='trivia.Player'),
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='trivia.Game'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
