# Generated by Django 2.2 on 2019-04-24 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0014_auto_20190424_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='p1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamep1', to='trivia.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='p2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamep2', to='trivia.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trivia.TriviaQuestion'),
        ),
        migrations.AlterField(
            model_name='game',
            name='questionNum',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamewinner', to='trivia.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='choice',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trivia.Game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
