# Generated by Django 2.2 on 2019-04-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0016_auto_20190424_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='next',
            field=models.BooleanField(default=False),
        ),
    ]
