# Generated by Django 2.2 on 2019-04-28 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0017_player_next'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='questionNum',
        ),
    ]
